apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: ralonso
spec:
  limits:
  - type: Container
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: "0.5"
      memory: 500Mi
    default:
      cpu: "0.5"
      memory: 500Mi
    defaultRequest:
      cpu: "0.5"
      memory: 500Mi