apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - name: nginx-vol
            mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes: 
        - name: nginx-vol
          configMap:
            name: index-config-map